#!/bin/bash

SESSION_NAME=${1:- 󰊠 }

tmux new-session -d -s "$SESSION_NAME" -n nvim
tmux new-window -t "$SESSION_NAME" -n git
tmux new-window -t "$SESSION_NAME" -n nix
#tmux new-window -t "$SESSION_NAME" -n email
tmux new-window -t "$SESSION_NAME" -n fish
tmux select-window -t "$SESSION_NAME":nvim
tmux attach-session -t "$SESSION_NAME"
